# Generated by Django 3.2.3 on 2021-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('tytul', models.CharField(max_length=200)),
                ('gatunek', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=13)),
            ],
        ),
    ]
