# Generated by Django 3.2.3 on 2021-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zespol', models.CharField(max_length=200)),
                ('tytul', models.CharField(max_length=200)),
                ('gatunek', models.CharField(max_length=200)),
                ('lista_utworow', models.CharField(max_length=200)),
                ('czas_trwania', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezyser', models.CharField(max_length=200)),
                ('tytul', models.CharField(max_length=200)),
                ('gatunek', models.CharField(max_length=200)),
                ('czas_trwania', models.IntegerField()),
            ],
        ),
    ]
