# Generated by Django 3.2.3 on 2021-06-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0002_cd_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='wypozyczajacy',
            field=models.CharField(default='maciek', max_length=13),
        ),
    ]
