# Generated by Django 3.2.3 on 2021-06-05 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0004_auto_20210606_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='user',
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='wypozyczajacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
