# Generated by Django 3.2.3 on 2021-06-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0007_alter_ksiazka_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
