# Generated by Django 3.2.3 on 2021-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0008_alter_ksiazka_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('rezyser', 'tytul', 'czas_trwania')},
        ),
        migrations.AlterUniqueTogether(
            name='ksiazka',
            unique_together={('tytul', 'gatunek', 'ISBN')},
        ),
    ]
