# Generated by Django 3.2.3 on 2021-06-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0009_auto_20210606_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ksiazka',
            unique_together={('autor', 'tytul', 'gatunek')},
        ),
    ]
