# Generated by Django 3.2.3 on 2021-06-07 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0011_auto_20210607_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CD',
            new_name='Plyta',
        ),
    ]
