# Generated by Django 3.2.3 on 2021-06-08 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0012_rename_cd_plyta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('rzecz', models.CharField(max_length=200)),
                ('item_id', models.IntegerField()),
                ('data_wypozyczenia', models.DateTimeField()),
                ('data_zwrotu', models.DateTimeField(blank=True, null=True)),
                ('wypozyczajacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
