# Generated by Django 3.2.3 on 2021-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0013_wypozyczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenie',
            name='tytul',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
